/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pdfslider.frames;

import br.com.pdfslider.listeners.Listener_Slider;
import br.com.pdfslider.util.Utilidades;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JToolBar;


public final class Form_Slider extends javax.swing.JFrame {

    private static final long serialVersionUID = -7739760390540710937L;
    private final Listener_Slider listener;

    /**
     * Creates new form Form_Slider
     */
    public Form_Slider() {
        setImageIcon();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        listener = new Listener_Slider(this);
    }

    public void setImageIcon() {
        Utilidades.setImageIcon(this);
    }

    public JMenuItem getItemFechar() {
        return itemFechar;
    }

    public JPanel getPainelMain() {
        return painelMain;
    }

    public JLabel getLbPage() {
        return lbPage;
    }

    public JButton getBtAnvacar() {
        return btAnvacar;
    }

    public JButton getBtPausar() {
        return btPausar;
    }

    public JButton getBtVoltar() {
        return btVoltar;
    }

    public JToolBar getControlBar() {
        return controlBar;
    }

    public JLabel getLbPaginas() {
        return lbPaginas;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMain = new javax.swing.JPanel();
        lbPage = new javax.swing.JLabel();
        controlBar = new javax.swing.JToolBar();
        btVoltar = new javax.swing.JButton();
        btPausar = new javax.swing.JButton();
        btAnvacar = new javax.swing.JButton();
        lbPaginas = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        itemFechar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PDF Slider Viewer");

        controlBar.setRollover(true);

        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdfslider/img/back.png"))); // NOI18N
        btVoltar.setActionCommand("voltar");
        btVoltar.setFocusable(false);
        btVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        controlBar.add(btVoltar);

        btPausar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdfslider/img/pause.png"))); // NOI18N
        btPausar.setActionCommand("pausar");
        btPausar.setFocusable(false);
        btPausar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPausar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        controlBar.add(btPausar);

        btAnvacar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pdfslider/img/next.png"))); // NOI18N
        btAnvacar.setActionCommand("avancar");
        btAnvacar.setFocusable(false);
        btAnvacar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAnvacar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        controlBar.add(btAnvacar);

        lbPaginas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbPaginas.setText("<html>\n<b>Páginas</b><br/>\n<p>0/0</p>\n</html>");
        lbPaginas.setToolTipText("");
        controlBar.add(lbPaginas);

        javax.swing.GroupLayout painelMainLayout = new javax.swing.GroupLayout(painelMain);
        painelMain.setLayout(painelMainLayout);
        painelMainLayout.setHorizontalGroup(
            painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(controlBar, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );
        painelMainLayout.setVerticalGroup(
            painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMainLayout.createSequentialGroup()
                .addComponent(controlBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPage, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
        );

        menuBar.setMinimumSize(new java.awt.Dimension(0, 0));
        menuBar.setPreferredSize(new java.awt.Dimension(0, 0));

        menuArquivo.setText("Arquivo");

        itemFechar.setText("Fechar");
        itemFechar.setActionCommand("fechar");
        menuArquivo.add(itemFechar);

        menuBar.add(menuArquivo);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Slider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Slider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Slider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Slider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Slider().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnvacar;
    private javax.swing.JButton btPausar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JToolBar controlBar;
    private javax.swing.JMenuItem itemFechar;
    private javax.swing.JLabel lbPage;
    private javax.swing.JLabel lbPaginas;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel painelMain;
    // End of variables declaration//GEN-END:variables
}
